In [18]:
import pandas as pd

In [19]:
df1=pd.read_csv('/Users/michaelrosen/Desktop/Housing_Modeling/Data/la_apts_SFV_geometry_May25.csv')
df2=pd.read_csv('/Users/michaelrosen/Desktop/Housing_Modeling/Data/wst_5-25_geometry.csv')
df3=pd.read_csv('/Users/michaelrosen/Desktop/Housing_Modeling/Data/lac_5-23_latlong.csv')
df4=pd.read_csv('/Users/michaelrosen/Desktop/Housing_Modeling/Data/sgv_latlong.csv')
df5=pd.read_csv('/Users/michaelrosen/Desktop/Housing_Modeling/Data/lgb_latlong.csv')

In [20]:
df1['y'] = df1['latlon'].apply(lambda x: x[0])
df1['x'] = df1['latlon'].apply(lambda x: x[1])

In [26]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0.1     3000 non-null   int64
 1   Unnamed: 0       3000 non-null   int64
 2   posted           3000 non-null   object
 3   neighborhood     3000 non-null   object
 4   post title       3000 non-null   object
 5   number bedrooms  2530 non-null   float64
 6   sqft             2646 non-null   float64
 7   URL              3000 non-null   object
 8   price            2965 non-null   object
 9   latlon           3000 non-null   object
 10  y                3000 non-null   object
 11  x                3000 non-null   object
dtypes: float64(2), int64(2), object(8)
memory usage: 281.4+ KB

In [3]:
df=pd.concat([df1, df2, df3, df4, df5])

In [8]:
df = df.drop(columns=['Unnamed: 0.1','Unnamed: 0'])

In [22]:
df.to_csv('')

,posted,neighborhood,post title,number bedrooms,sqft,URL,price,latlon,y,x
2187,2022-04-26 12:18,(Santa Fe Springs),1x1 Available Now! Don't Miss Out!! Call For M...,1.0,650.0,https://losangeles.craigslist.org/sgv/apa/d/wh...,"2,372","['33.965213', '-118.082800']",33.965213,-118.082800
861,2022-05-22 03:01,"(505 N. Figueroa St., Los Angeles, CA)","24-Hour Doorman, Sand Volleyball Court, EV Cha...",2.0,946.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,968","['34.061400', '-118.238500']",34.061400,-118.238500
1296,2022-05-21 14:16,"(3205 Los Feliz Boulevard, Los Angeles, CA)","Sit Back, Relax. Your New View Awaits.",NaN,425.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,050","['34.112100', '-118.259400']",34.112100,-118.259400
204,2022-05-24 15:35,(san fernando valley),"On-site Laundry, Parking, Pool",2.0,875.0,https://losangeles.craigslist.org/sfv/apa/d/bu...,"2,979","['34.169000', '-118.344200']",NaN,NaN
1980,2022-04-30 09:47,"(Long Beach, Signal Hill, Lakewood Area)","‚è∞ DON'T HESITATE on 2 +1 close to Pool, BBQ, F...",2.0,950.0,https://losangeles.craigslist.org/lgb/apa/d/lo...,"2,365","['33.844416', '-118.165901']",33.844416,-118.165901
216,2022-05-25 10:01,"(5910 Orange Ave, Apt.# D, Long Beach, CA 90805)",Open House - Will work with bad credit - 1 br/...,1.0,NaN,https://losangeles.craigslist.org/wst/apa/d/lo...,"1,750","['33.862173', '-118.177402']",33.862173,-118.177402
1747,2022-05-23 14:53,(westside-southbay-310),Lynwood Harris Courtyard-1 Bedrooms,1.0,NaN,https://losangeles.craigslist.org/wst/apa/d/ly...,"1,695","['33.910716', '-118.197461']",33.910716,-118.197461
1007,2022-05-24 11:26,"(840 Larrabee Street, West Hollywood, CA)","Heated resort-style pool, 24-Hour laundry cent...",NaN,414.0,https://losangeles.craigslist.org/wst/apa/d/we...,"2,553","['34.090600', '-118.378800']",34.090600,-118.378800
1561,2022-05-23 17:39,"(Westwood 90024/UCLA, Brentwood, West LA, Bev...",Top Floor Westwood 2 Bed / 2 Bath Penthouse w/...,2.0,NaN,https://losangeles.craigslist.org/wst/apa/d/lo...,"3,895","['34.057597', '-118.444437']",34.057597,-118.444437
1569,2022-05-06 17:53,(WEST COVINA),JR. ONE BEDROOM ONE BATH AVAILABLE TO MOVE IN ...,1.0,600.0,https://losangeles.craigslist.org/sgv/apa/d/co...,"2,046","['34.070109', '-117.866594']",34.070109,-117.866594
193,2022-05-22 13:06,(san gabriel valley),"Reserved covered parking, Lush landscaped grou...",2.0,955.0,https://losangeles.craigslist.org/sgv/apa/d/ha...,"2,998","['33.990598', '-117.969885']",33.990598,-117.969885
1291,2022-05-12 11:40,(El Monte),Huge 2 bedroom 1 bath plus Loft in El Monte!!,2.0,1025.0,https://losangeles.craigslist.org/sgv/apa/d/el...,"2,275","['34.077400', '-118.053600']",34.077400,-118.053600
2586,2022-05-22 09:38,(san fernando valley),"Guest Parking, Outdoor Fireplaces, Two Cyber L...",1.0,NaN,https://losangeles.craigslist.org/sfv/apa/d/va...,"2,515","['34.200100', '-118.445600']",NaN,NaN
1120,2022-05-23 21:24,"(18414 W. Jakes Way, Los Angeles)",A Beautiful Place to Call Home,2.0,919.0,https://losangeles.craigslist.org/sfv/apa/d/ca...,NaN,"['34.413200', '-118.426000']",NaN,NaN
30,2022-05-24 17:09,(san fernando valley),"Dishwasher, Beautiful Landscaping, Cable Ready",2.0,997.0,https://losangeles.craigslist.org/sfv/apa/d/ca...,"2,217","['34.413200', '-118.426000']",NaN,NaN
1970,2022-05-20 14:54,(Los Angeles),Rooftop Penthouse with Private Elevator / DTLA...,1.0,NaN,https://losangeles.craigslist.org/lac/apa/d/lo...,"3,500","['34.062611', '-118.281508']",34.062611,-118.281508
410,2022-05-22 16:00,(South Gate),Rear Cottage,1.0,500.0,https://losangeles.craigslist.org/lac/apa/d/hu...,NaN,"['33.960668', '-118.211343']",33.960668,-118.211343
2353,2022-05-20 09:53,(Los Angeles),2 bed 1 bath Apartment in Silver Lake near Ech...,2.0,NaN,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,200","['34.076992', '-118.266659']",34.076992,-118.266659
508,2022-05-22 14:10,(Hollywood),"1Bd./1Ba. Central Air, Shimmering Swimming Poo...",1.0,492.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,285","['34.095370', '-118.350885']",34.095370,-118.350885
536,2022-05-22 13:44,"(Koreatown, Oakwood, Silverlake Adj)",140 N Hoover Efficiency Studio,NaN,350.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"1,395","['34.073545', '-118.284386']",34.073545,-118.284386