In [55]:
import pandas as pd
import requests
from requests import get
from bs4 import BeautifulSoup
import random
import time

In [2]:
df = pd.read_csv("la_apts 2.csv")
df.head()

,Unnamed: 0,posted,neighborhood,post title,number bedrooms,sqft,URL,price,latlon,lat
0,0,2022-05-18 12:56,(Los Angeles),2 BR/1BR cottage house for rent,2.0,NaN,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,600",NaN,"[None, None]"
1,1,2022-05-18 12:56,"(400 S Main St Los Angeles, CA)",Be Ready To Be Wowed. Huge Urban Loft. Great C...,NaN,1420.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"3,230",NaN,"[None, None]"
2,2,2022-05-18 12:56,(Hollywood),Spacious 2 Bedroom/2 Bath ~ Coming June!,2.0,1131.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"3,327",NaN,"[None, None]"
3,3,2022-05-18 12:54,"(909 W. Temple St., Los Angeles, CA)",City view and plenty of amenities!!!,2.0,948.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,995",NaN,"[None, None]"
4,4,2022-05-18 12:49,(North Westlake),"Wood Inspired Floors, Gym, Newly Built 1 Bedro...",1.0,1075.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,300",NaN,"[None, None]"

In [60]:
def get_latlong(url):
    r = requests.get(url)
    soup = BeautifulSoup(r.content)
    link = soup.find_all('div', class_='viewposting')
    lat = link[0]['data-latitude']
    long = link[0]['data-longitude']
    #time.sleep(random.uniform(1,4))
    #this code could be used to randomize the time between calls to craigslist and slow down the scraper, not sure if we need it
    return [lat, long]

In [28]:
test_lat, test_long = get_latlong(df.URL.loc[5])
print('lat is {}, long is {}'.format(test_lat, test_long))

lat is 34.250103, long is -118.502418

In [57]:
df['latlon'] = df.URL.head(5).apply(get_latlong)
df.head()

,Unnamed: 0,posted,neighborhood,post title,number bedrooms,sqft,URL,price,latlon,lat,long
0,0,2022-05-18 12:56,(Los Angeles),2 BR/1BR cottage house for rent,2.0,NaN,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,600","[34.048200, -118.334300]",34.048200,-118.334300
1,1,2022-05-18 12:56,"(400 S Main St Los Angeles, CA)",Be Ready To Be Wowed. Huge Urban Loft. Great C...,NaN,1420.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"3,230","[34.048212, -118.247207]",34.048212,-118.247207
2,2,2022-05-18 12:56,(Hollywood),Spacious 2 Bedroom/2 Bath ~ Coming June!,2.0,1131.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"3,327","[34.107400, -118.365200]",34.107400,-118.365200
3,3,2022-05-18 12:54,"(909 W. Temple St., Los Angeles, CA)",City view and plenty of amenities!!!,2.0,948.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,995","[34.061400, -118.238500]",34.061400,-118.238500
4,4,2022-05-18 12:49,(North Westlake),"Wood Inspired Floors, Gym, Newly Built 1 Bedro...",1.0,1075.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,300","[34.065915, -118.273467]",34.065915,-118.273467

In [44]:
df.drop(columns='lat', inplace=True)

In [58]:
df['lat'] = df['latlon'].head().apply(lambda x: x[0])
df['long'] = df['latlon'].head().apply(lambda x: x[1])

In [59]:
df.head()

,Unnamed: 0,posted,neighborhood,post title,number bedrooms,sqft,URL,price,latlon,lat,long
0,0,2022-05-18 12:56,(Los Angeles),2 BR/1BR cottage house for rent,2.0,NaN,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,600","[34.048200, -118.334300]",34.048200,-118.334300
1,1,2022-05-18 12:56,"(400 S Main St Los Angeles, CA)",Be Ready To Be Wowed. Huge Urban Loft. Great C...,NaN,1420.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"3,230","[34.048212, -118.247207]",34.048212,-118.247207
2,2,2022-05-18 12:56,(Hollywood),Spacious 2 Bedroom/2 Bath ~ Coming June!,2.0,1131.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"3,327","[34.107400, -118.365200]",34.107400,-118.365200
3,3,2022-05-18 12:54,"(909 W. Temple St., Los Angeles, CA)",City view and plenty of amenities!!!,2.0,948.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,995","[34.061400, -118.238500]",34.061400,-118.238500
4,4,2022-05-18 12:49,(North Westlake),"Wood Inspired Floors, Gym, Newly Built 1 Bedro...",1.0,1075.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,300","[34.065915, -118.273467]",34.065915,-118.273467

Some Next Thoughts:
We are going to need to make a bunch of calls to craigslist, one idea is that we could use the ScraperAPI there is a free trial for 5000 web requests, or it's 30 bucks for a month with 250,000 which seems like an ok deal to just not have to worry about being blocked

[ScraperAPI](https://www.scraperapi.com/)