In [4]:
import pandas as pd
import requests
from requests import get
from bs4 import BeautifulSoup
import random
import time

In [23]:
df = pd.read_csv("la_apts 2.csv")
df.drop(columns=['latlon', 'lat'], inplace=True)
df.head()

,Unnamed: 0,posted,neighborhood,post title,number bedrooms,sqft,URL,price
0,0,2022-05-18 12:56,(Los Angeles),2 BR/1BR cottage house for rent,2.0,NaN,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,600"
1,1,2022-05-18 12:56,"(400 S Main St Los Angeles, CA)",Be Ready To Be Wowed. Huge Urban Loft. Great C...,NaN,1420.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"3,230"
2,2,2022-05-18 12:56,(Hollywood),Spacious 2 Bedroom/2 Bath ~ Coming June!,2.0,1131.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"3,327"
3,3,2022-05-18 12:54,"(909 W. Temple St., Los Angeles, CA)",City view and plenty of amenities!!!,2.0,948.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,995"
4,4,2022-05-18 12:49,(North Westlake),"Wood Inspired Floors, Gym, Newly Built 1 Bedro...",1.0,1075.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,300"

In [14]:
def get_latlong(url):
    r = requests.get(url)
    soup = BeautifulSoup(r.content)
    try:
        link = soup.find_all('div', class_='viewposting')
        lat = link[0]['data-latitude']
        long = link[0]['data-longitude']
        time.sleep(random.uniform(.5,3))
    #this code could be used to randomize the time between calls to craigslist and slow down the scraper, not sure if we need it
        return [lat, long]
    except:
        return [None, None]

In [15]:
test_lat, test_long = get_latlong(df.URL.loc[5])
print('lat is {}, long is {}'.format(test_lat, test_long))

lat is 34.250103, long is -118.502418

In [25]:
df['latlon'] = df.URL.head(150).apply(get_latlong)
df.head(150)

,Unnamed: 0,posted,neighborhood,post title,number bedrooms,sqft,URL,price,latlon
0,0,2022-05-18 12:56,(Los Angeles),2 BR/1BR cottage house for rent,2.0,NaN,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,600","[34.048200, -118.334300]"
1,1,2022-05-18 12:56,"(400 S Main St Los Angeles, CA)",Be Ready To Be Wowed. Huge Urban Loft. Great C...,NaN,1420.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"3,230","[34.048212, -118.247207]"
2,2,2022-05-18 12:56,(Hollywood),Spacious 2 Bedroom/2 Bath ~ Coming June!,2.0,1131.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"3,327","[34.107400, -118.365200]"
3,3,2022-05-18 12:54,"(909 W. Temple St., Los Angeles, CA)",City view and plenty of amenities!!!,2.0,948.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,995","[34.061400, -118.238500]"
4,4,2022-05-18 12:49,(North Westlake),"Wood Inspired Floors, Gym, Newly Built 1 Bedro...",1.0,1075.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,300","[34.065915, -118.273467]"
...,...,...,...,...,...,...,...,...,...
145,145,2022-05-18 12:38,(Santa Monica),nice and clean 2 bedroom and 2 bathrooms in Sa...,2.0,1300.0,https://losangeles.craigslist.org/lac/apa/d/sa...,938,"[34.040185, -118.471323]"
146,146,2022-05-18 12:38,"(1026 S Broadway, Los Angeles, CA)",2B x2B in DTLA!@!,2.0,946.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"3,355","[34.043400, -118.271600]"
147,147,2022-05-18 12:38,(HOLLYWOOD/HANCOCK PARK ADJ),"2BDRM, 1BATH,REMODELED! PARKING, HARDWOOD, FRI...",2.0,800.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,295","[34.092793, -118.334510]"
148,148,2022-05-18 12:37,(Hollywood),1 Month Free | Renovated 1 Bedroom TH in Holly...,1.0,775.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,750","[34.093650, -118.326910]"
149,149,2022-05-18 12:37,(Hollywood),Vinyl Plank Flooring ^ Patio/Balcony ^ A/C ^ 2...,2.0,NaN,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,295","[34.098943, -118.305834]"

0    34.048200
1    34.048212
2    34.107400
3    34.061400
4    34.065915
Name: latlon, dtype: object

In [43]:
#df.drop(columns=['long', 'lat'], inplace=True)
df['y'] = df['latlon'].head(150).apply(lambda x: x[0])
df['x'] = df['latlon'].head(150).apply(lambda x: x[1])

In [44]:
df.head(150)

,Unnamed: 0,posted,neighborhood,post title,number bedrooms,sqft,URL,price,latlon,y,x
0,0,2022-05-18 12:56,(Los Angeles),2 BR/1BR cottage house for rent,2.0,NaN,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,600","[34.048200, -118.334300]",34.048200,-118.334300
1,1,2022-05-18 12:56,"(400 S Main St Los Angeles, CA)",Be Ready To Be Wowed. Huge Urban Loft. Great C...,NaN,1420.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"3,230","[34.048212, -118.247207]",34.048212,-118.247207
2,2,2022-05-18 12:56,(Hollywood),Spacious 2 Bedroom/2 Bath ~ Coming June!,2.0,1131.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"3,327","[34.107400, -118.365200]",34.107400,-118.365200
3,3,2022-05-18 12:54,"(909 W. Temple St., Los Angeles, CA)",City view and plenty of amenities!!!,2.0,948.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,995","[34.061400, -118.238500]",34.061400,-118.238500
4,4,2022-05-18 12:49,(North Westlake),"Wood Inspired Floors, Gym, Newly Built 1 Bedro...",1.0,1075.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,300","[34.065915, -118.273467]",34.065915,-118.273467
...,...,...,...,...,...,...,...,...,...,...,...
145,145,2022-05-18 12:38,(Santa Monica),nice and clean 2 bedroom and 2 bathrooms in Sa...,2.0,1300.0,https://losangeles.craigslist.org/lac/apa/d/sa...,938,"[34.040185, -118.471323]",34.040185,-118.471323
146,146,2022-05-18 12:38,"(1026 S Broadway, Los Angeles, CA)",2B x2B in DTLA!@!,2.0,946.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"3,355","[34.043400, -118.271600]",34.043400,-118.271600
147,147,2022-05-18 12:38,(HOLLYWOOD/HANCOCK PARK ADJ),"2BDRM, 1BATH,REMODELED! PARKING, HARDWOOD, FRI...",2.0,800.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,295","[34.092793, -118.334510]",34.092793,-118.334510
148,148,2022-05-18 12:37,(Hollywood),1 Month Free | Renovated 1 Bedroom TH in Holly...,1.0,775.0,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,750","[34.093650, -118.326910]",34.093650,-118.326910
149,149,2022-05-18 12:37,(Hollywood),Vinyl Plank Flooring ^ Patio/Balcony ^ A/C ^ 2...,2.0,NaN,https://losangeles.craigslist.org/lac/apa/d/lo...,"2,295","[34.098943, -118.305834]",34.098943,-118.305834

Some Next Thoughts:
We are going to need to make a bunch of calls to craigslist, one idea is that we could use the ScraperAPI there is a free trial for 5000 web requests, or it's 30 bucks for a month with 250,000 which seems like an ok deal to just not have to worry about being blocked

[ScraperAPI](https://www.scraperapi.com/)

[None, None]